# Generated by Django 5.2.6 on 2025-09-25 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=200)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('importancia', models.BooleanField(default=False)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='api.itinerario')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('tipo_viaje', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('negocios', 'Negocios')], default='vacaciones', max_length=20)),
                ('viajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itinerario',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='api.viaje'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('boleto', 'Boleto de Avión/Tren'), ('hotel', 'Reserva de Hotel'), ('restaurante', 'Reserva de Restaurante'), ('seguro', 'Póliza de Seguro'), ('otro', 'Otro Documento')], default='boleto', max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.viaje')),
            ],
        ),
    ]
